const keyboards = {
  'ru-RU': [
    [
      { value: 'й', status: '' },
      { value: 'ц', status: '' },
      { value: 'у', status: '' },
      { value: 'к', status: '' },
      { value: 'е', status: '' },
      { value: 'н', status: '' },
      { value: 'г', status: '' },
      { value: 'ш', status: '' },
      { value: 'щ', status: '' },
      { value: 'з', status: '' },
      { value: 'х', status: '' },
      { value: 'ъ', status: '' },
    ],
    [
      { value: 'ф', status: '' },
      { value: 'ы', status: '' },
      { value: 'в', status: '' },
      { value: 'а', status: '' },
      { value: 'п', status: '' },
      { value: 'р', status: '' },
      { value: 'о', status: '' },
      { value: 'л', status: '' },
      { value: 'д', status: '' },
      { value: 'ж', status: '' },
      { value: 'э', status: '' },
    ],
    [
      { value: 'backSpace', status: '' },
      { value: 'я', status: '' },
      { value: 'ч', status: '' },
      { value: 'с', status: '' },
      { value: 'м', status: '' },
      { value: 'и', status: '' },
      { value: 'т', status: '' },
      { value: 'ь', status: '' },
      { value: 'б', status: '' },
      { value: 'ю', status: '' },
      { value: 'enter', status: '' },
    ],
  ],
  'en-EN': [
    [
      { value: 'q', status: '' },
      { value: 'w', status: '' },
      { value: 'e', status: '' },
      { value: 'r', status: '' },
      { value: 't', status: '' },
      { value: 'y', status: '' },
      { value: 'u', status: '' },
      { value: 'i', status: '' },
      { value: 'o', status: '' },
      { value: 'p', status: '' },
    ],
    [
      { value: 'a', status: '' },
      { value: 's', status: '' },
      { value: 'd', status: '' },
      { value: 'f', status: '' },
      { value: 'g', status: '' },
      { value: 'h', status: '' },
      { value: 'j', status: '' },
      { value: 'k', status: '' },
      { value: 'l', status: '' },
    ],
    [
      { value: 'backSpace', status: '' },
      { value: 'z', status: '' },
      { value: 'x', status: '' },
      { value: 'c', status: '' },
      { value: 'v', status: '' },
      { value: 'b', status: '' },
      { value: 'n', status: '' },
      { value: 'm', status: '' },
      { value: 'enter', status: '' },
    ],
  ],
};

export default keyboards;
