const keyboardRuLang = [
  [
    { value: 'й', status: '' },
    { value: 'ц', status: '' },
    { value: 'у', status: '' },
    { value: 'к', status: '' },
    { value: 'е', status: '' },
    { value: 'н', status: '' },
    { value: 'г', status: '' },
    { value: 'ш', status: '' },
    { value: 'щ', status: '' },
    { value: 'з', status: '' },
    { value: 'х', status: '' },
    { value: 'ъ', status: '' },
  ],
  [
    { value: 'ф', status: '' },
    { value: 'ы', status: '' },
    { value: 'в', status: '' },
    { value: 'а', status: '' },
    { value: 'п', status: '' },
    { value: 'р', status: '' },
    { value: 'о', status: '' },
    { value: 'л', status: '' },
    { value: 'д', status: '' },
    { value: 'ж', status: '' },
    { value: 'э', status: '' },
  ],
  [
    { value: 'backSpace', status: '' },
    { value: 'я', status: '' },
    { value: 'ч', status: '' },
    { value: 'с', status: '' },
    { value: 'м', status: '' },
    { value: 'и', status: '' },
    { value: 'т', status: '' },
    { value: 'ь', status: '' },
    { value: 'б', status: '' },
    { value: 'ю', status: '' },
    { value: 'ввод', status: '' },
  ],
];

export default keyboardRuLang;
