const wordsEnLang = [
  { word: 'apple', number: 1 },
  { word: 'table', number: 2 },
  { word: 'coach', number: 3 },
  { word: 'sport', number: 4 },
  { word: 'place', number: 5 },
  { word: 'grass', number: 6 },
  { word: 'glass', number: 7 },
  { word: 'glass', number: 8 },
  { word: 'glass', number: 9 },
  { word: 'glass', number: 10 },
  { word: 'glass', number: 11 },
  { word: 'glass', number: 12 },
  { word: 'glass', number: 13 },
  { word: 'glass', number: 14 },
  { word: 'glass', number: 15 },
  { word: 'glass', number: 16 },
  { word: 'glass', number: 17 },
  { word: 'glass', number: 18 },
  { word: 'glass', number: 19 },
  { word: 'glass', number: 20 },
  { word: 'glass', number: 21 },
  { word: 'glass', number: 22 },
  { word: 'glass', number: 23 },
  { word: 'glass', number: 24 },
  { word: 'glass', number: 25 },
  { word: 'glass', number: 26 },
  { word: 'glass', number: 27 },
];

export default wordsEnLang;
